### ISSUE TITLE
Childs animations not working on "Pie Mode"

### ISSUE THREAD

**Issue by antoni-alvarez** [dmitry-zaitsev/CircleLayout#6]
Tested on Nexus 4 with Android 4.3. 

I modified the default sample project to make it easy to reproduce the issue:

https://www.dropbox.com/s/q52su3r7lydsvfs/CircleLayoutTestCase.zip

**Comment by dmitry-zaitsev** [comment]
Oh, excuse me for lack of documentation about this problem.
The thing is that "pie" mode is actually quite complicated and performs very "heavy" drawing operations, so that's why animations are not supported (and even if they were, they would still be laggy)
